### ISSUE TITLE
그래프 정보 관련 문의

### ISSUE THREAD

**Issue by sousky-j** [kimsangho611/DS_Project_3_2024_2#10]
이전 issue 중에서 txt 그래프 정보로 사이즈보다 큰 값이 들어오는 것을 예외처리 해야 한다는 것을 보았습니다.
반대로 아래와 같은 형식의 데이터가 들어오면 2번 vertex는 존재하지 않는 건가요?
L
3
0
1 2
1
0 3

또한 아래와 같은 형식인, conneted graph가 아닌 그래프가 들어올 수 있나요? (이에 대한 예외처리나 connected graph만 들어온다는 가정에 대한 질문)

L
3
0
2 2
1
2
0 3

**Comment by sousky-j** [comment]
2번 질문에 대해 제안서에서 "만약 edge가 없는 vertex의 경우 (형식-1)만 존재할 수 있다."라는 부분 확인하였습니다.
그러면 matrix 데이터는 입력된 size만큼 row가 있다고 가정하나요?

**Comment by kimsangho611** [comment]
matrix의 경우는 당연히 입력된 size만큼의 row가 있다고 가정합니다.
