### ISSUE TITLE
getAdjacentEdges 함수 질문

### ISSUE THREAD

**Issue by hanasol** [kimsangho611/DS_Project_3_2024_2#12]
제가 이해하기로 이 함수가 이어져 있는 간선의 정보를 반환하는 함수라고 생각했는데,  List 클래스와 Matrix 클래스 에서 모두 void getAdjacentEdges(int vertex, map<int, int>* m)의 함수로 되어있습니다. List 클래스의 멤버는 map<int, int>* 로 되어있으나 Matrix 클래스의 멤버는 int**이어서 양식에 맞지 않다고 생각했습니다. 이에 대한 부분이랑 getAdjacenDeges 함수가 어떤 기능을 하는지 궁금합니다.

**Comment by kimsangho611** [comment]
해당 함수는 List와 Matrix로 구성된 데이터에서 vertex와 이어져 있는 간선을 모두 반환하는 함수입니다. 
해당 함수가 구체적으로 어떤 기능을 하는지는 좀 더 생각해보길 바랍니다.
