### ISSUE TITLE
GraphMethod 문의드립니다.

### ISSUE THREAD

**Issue by DanielRho** [kimsangho611/DS_Project_3_2024_2#13]
1. 그래프 데이터의 방향성의 질문에 대한 답변으로
데이터 추가 없이 데이터에서 가중치가 없다고 가정하고 구현하라고 하셨는데
[0] -> (1,6) -> (2,2)
[1] -> (3,5)
[2] -> (1,7) -> (4,3) -> (5,8)
[3] -> (6,3)
[4] -> (3,4)
[5] -> (6,1)
[6] -> (4,10)
위 그래프에서 start vertex가 2일 때
제안서 예시 결과는 2 -> 0 -> 1 -> 3 -> 4 -> 6 -> 5 라고 나와있는데
데이터 추가 없이 구현하였을 때
실제 출력 결과는 0이 포함이 안된 2 -> 1 -> 3 -> 6 -> 4 -> 5 이렇게 나오는 것이 맞는지 
또는 제안서 예시처럼 결과가 나와야 하는 것이 맞는지 궁금합니다.

2. 출력 포맷과 동일한 출력을 위해 GraphMethod에 있는 모든 함수에서 인자를 추가하여 구현해도 되는지 궁금합니다.

**Comment by kimsangho611** [comment]
1. 제안서는 단순히 출력 예시를 돕기 위한 것입니다. 학생분이 이해하신 것이 맞습니다.
2. 추가해도 됩니다.
