### ISSUE TITLE
매개변수 변경 질문입니다.

### ISSUE THREAD

**Issue by cssrex** [kimsangho611/DS_Project_3_2024_2#14]
void getAdjacentEdges(int vertex, map<int, int>* m)를
void getAdjacentEdges(int vertex, map<int, int>*& m)로 바꾸고,

bool DFS_R(Graph* graph, vector<bool>* visit, int vertex)를
bool DFS_R(Graph* graph, vector<bool>& visit, int vertex)로 바꿔도 괜찮을 까요?

**Comment by kimsangho611** [comment]
변경해도 무방합니다.
