### ISSUE TITLE
graph_L, M txt 파일 질문입니다.

### ISSUE THREAD

**Issue by 425range** [kimsangho611/DS_Project_3_2024_2#15]
graph_L.txt, graph_M.txt 파일의 첫 줄에 있는 L과 M은 어떤 역할을 하나요?
파일명으로 어떤 타입의 데이터가 들어있는지 구분이 되어서 첫줄이 어떤 역할을 하는지 모르겠습니다.
예를 들어 graph_M.txt 파일인데 첫 줄이 L인 경우가 나올 수 있나요?
감사합니다.

**Comment by kimsangho611** [comment]
L과 M은 단순히 타입을 구분하는 역할로 _M.txt인데 첫줄에 L인 경우는 없습니다.

**Comment by 425range** [comment]
감사합니다.
