### ISSUE TITLE
Dijkstra 관련 질문입니다.

### ISSUE THREAD

**Issue by cssrex** [kimsangho611/DS_Project_3_2024_2#16]
음의 가중치 간선이 있더라도, 해당 간선까지의 경로가 없어서 계산에 이용되지 않을 경우에는 에러를 출력하나요? 아니면 정상적으로 최단 경로를 출력하나요? 예를 들어서

0->1 로 가는 간선의 가중치가 1이고
2->3 로 가는 간선의 가중치가 -1인
그래프가 있다고 하고, 0에서 dijkstra를 실행한다고 하면
2->3으로 가는 음의 간선은 이용되지 않으므로
[1] 0 -> 1 (1)
[2] x
[3] x
로 출력이 되는 게 맞는지, 혹은 에러 메시지를 출력하는지 궁금합니다.

**Comment by kimsangho611** [comment]
다익스트라 알고리즘을 테스트시 음의 가중치는 고려하지 않습니다.

**Comment by cssrex** [comment]
그렇다면 아예 접근이 불가능한 음의 가중치가 있더라도 에러를 띄우라는 뜻인거죠?

**Comment by cssrex** [comment]
> 다익스트라 알고리즘을 테스트시 음의 가중치는 고려하지 않습니다.

그렇다면 시작 지점에서 아예 접근 하지 못하는 음의 가중치는 신경 쓰지 않든지, 
혹은 접근을 못하더라도 음의 가중치가 있다면 에러를 띄우든지 둘 중 어떻게 구현하든 상관 없는건가요?

**Comment by kimsangho611** [comment]
상관없습니다. 

앞에서 답변한 것처럼 다익스트라 알고리즘을 채점시 음의 가중치가 있는 경우는 테스트하지 않습니다.
