### ISSUE TITLE
Kruskal 관련 질문

### ISSUE THREAD

**Issue by hanasol** [kimsangho611/DS_Project_3_2024_2#17]
functional requirement부분에서 "현재 그래프의 MST를 구하고, MST를 구성하는 edge들의 weight 값을 
오름차순으로 출력하고 weight의 총합을 출력 파일(log.txt)에 출력한다." 라고 되어있는데 
제가 Print fromat을 보고 이해했을 때, 노드 번호(weight)의 양식으로 출력이 된다고 생각했고, 이렇게 되면 노드 번호의 오름차순으로 정렬하는 방식으로 보여지는데 어떤 값을 기준으로 오름차순 정렬하는게 맞는지 궁금합니다

**Comment by kimsangho611** [comment]
노드 번호를 기준으로 정렬하면 됩니다.
