### ISSUE TITLE
출력 관련 질문입니다.

### ISSUE THREAD

**Issue by cssrex** [kimsangho611/DS_Project_3_2024_2#19]
스켈레톤 코드에서 matrix를 PRINT 할 때에는 각 항목이 tab으로 구분되어 있는데
pdf에서는 띄어쓰기 두칸으로 되어있는거 같아서 어떻게 해야할지 궁금합니다.
마찬가지로 FLOYD도 어떻게 해야 할지 알고 싶습니다.

추가로 ofstream을 graph의 속성으로 추가해도 되는지, 그리고 이에 따라 graph 관련 클래스들의 생성자로 fout을 받도록 수정해도 되는지 궁금합니다.

**Comment by kimsangho611** [comment]
1. 스켈레톤에 주어진 대로 사용하시면 됩니다.

2. 수정해도 됩니다.
