### ISSUE TITLE
함수 관련 질문 드립니다.

### ISSUE THREAD

**Issue by zerobak13** [kimsangho611/DS_Project_3_2024_2#2]
1.printGraph함수가  cout을 사용하여 구현되어있는데 수정해서 log.txt에 출력되게 하면 되나요?
2.bool BFS(Graph* graph, int vertex)같은 함수에서 결과를 log.txt에 출력하기 위해 인자를 추가해도 되나요?

**Comment by kimsangho611** [comment]
1. 네 맞습니다

2. 추가해도 됩니다.
