### ISSUE TITLE
그래프 데이터 노드 번호

### ISSUE THREAD

**Issue by sousky-j** [kimsangho611/DS_Project_3_2024_2#20]
이전 issue 중에서 노드 번호가 존재하지 않으면 예외처리 해야한다고 하셨는데
노드 번호가 1,2,3.... 이렇게 증가하는 것이 아니라 중간에 비어있다면 없는 노드라고 보고 이후 명령어의 그래프 연산을 수행해야 하는지, 아니면 txt가 잘못되었다고 판단을 하여 에러코드를 출력해야 하는지 질문드립니다.

**Comment by sousky-j** [comment]
이전에 입력받아 graph에 저장된 데이터도 에러코드를 출력한다면 다 지워야 하는지도 여쭤봅니다.

**Comment by kimsangho611** [comment]
이전 issue들은 노드 번호가 존재하지 않으면 예외처리하라는 것이 아니라 입력 그래프 크기보다 큰 노드가 존재하는 경우 예외처리하라는 것입니다. 

노드 번호가 중간에 비어 있다는 것이 정확히 뭘 말하고 싶은지는 잘 모르겠습니다.
1. 특정 노드에 에지가 없는 경우를 말하는 거라면 연결되지 않은 채로 그래프 연산을 수행하면 됩니다. 
2. 에지가 없는 노드가 txt 파일에 존재하지 않는 경우를 말하는 거라면 에러코드를 출력하면 됩니다. 
3. 기존에 그래프가 존재하는데 새로운 LOAD 명령어 수행시 에러코드를 내는 경우 기존 그래프를 유지하면 됩니다.

**Comment by sousky-j** [comment]
L
3
0
2 2
2
0 3
이런 식으로 중간에 비어있는 노드가 있는지 질문드린 것이었습니다.
이럴 때의 예외 처리에 대해서 여쭤봤습니다.

**Comment by sousky-j** [comment]
> L 3 0 2 2 2 0 3 이런 식으로 중간에 비어있는 노드가 있는지 질문드린 것이었습니다. 이럴 때의 예외 처리에 대해서 여쭤봤습니다.

2번 사항으로 알고 하겠습니다
