### ISSUE TITLE
행 열 관련 질문

### ISSUE THREAD

**Issue by 0yunse0** [kimsangho611/DS_Project_3_2024_2#21]
프로젝트 설명 pdf에서 'Matrix그래프의 경우 표1-2의 (형식-3)과 같이 그래프의 정보가 저장되어 있다. 행렬의 행과 열은 각각 to vertex와 from vertex를 의미'한다고 써져있는데,
강의 자료와 6번 issue에서의 DFS 예시, pdf의 '그림 1 프로그램 구성' 표를 참고했을 땐 행이 from vertex, 열이 to vertex로 사용되고 있습니다.
행과 열이 각각 무엇이 form vertex, to vertex인지 궁금합니다.

**Comment by kimsangho611** [comment]
행과 열은 각각 from vertex, to vertex입니다.
