### ISSUE TITLE
방향성에 관한 질문

### ISSUE THREAD

**Issue by ripplelover** [kimsangho611/DS_Project_3_2024_2#22]
![image](https://github.com/user-attachments/assets/d58a2415-20ac-4154-b340-13bb63132d02)
![image](https://github.com/user-attachments/assets/894b66ca-cb97-4186-a2c7-ecbf89b4fc3a)

DFS의 경우 방향성이 없다고 가정하여 간선이 단방향이라 하더라도 탐색 시 양방향으로 연결된 것처럼 처리를 하라는 것으로 받아들여서
양방향으로 구현을 하였을 경우.
제안서의 예시대로 아래와 같이 결과가 나오는 것을 확인할 수 있습니다.
 ======== DFS ========
 startvertex: 0
 0 -> 1 -> 2 -> 4 -> 3 -> 6 -> 5
 =====================
 
 그러나 다시 이를 단방향으로 구현을 하게 될 경우.
 아래와 같이 결과가 나오는 것을 확인할 수 있습니다.
======== DFS ========
startvertex: 0
0 -> 1 -> 3 -> 6 -> 4 -> 2 -> 5
=====================

현재 BFS, DFS, DFS_R 및 KRUSKAL의 경우 방향성이 없다고 가정을 하고 구현을 해야 하는지 아니면 단방향으로만 가능하게 구현을 해야하는지에 대한 정확한 여부를 알려주시면 감사하겠습니다.

**Comment by kimsangho611** [comment]
제안서에 명시된 대로 방향성 없다고 가정하면 됩니다.
