### ISSUE TITLE
BFS, DFS 관련 질문입니다.

### ISSUE THREAD

**Issue by cssrex** [kimsangho611/DS_Project_3_2024_2#23]
입력받은 그래프가 여러개의 부분 그래프로 나뉘어 져있는 형태일 경우에는 모든 정점을 방문할 수 없으므로 에러를 출력해야 하는지, 혹은 방문 가능한 정점을 방문 순서대로 출력하는 것인지 궁금합니다.
 또한 극단적으로 간선이 없는 그래프인 경우에는 에러를 출력하는게 맞는지,  아니면 자기 자신 번호만 출력하는 것인지 궁금합니다.

**Comment by kimsangho611** [comment]
1. 방문 가능한 정점을 출력하면 됩니다.
2. 해당 경우는 채점시 고려하지 않을 예정이니 에러를 출력하시면 될거 같습니다.
