### ISSUE TITLE
graph.txt 관련 질문

### ISSUE THREAD

**Issue by cha-a-ni** [kimsangho611/DS_Project_3_2024_2#24]
graph.txt 파일 하나로 그 내부에서 L인지 M인지 판단해서 그에 맞는 그래프를 만드는 건가요? 아니면 graph_L, graph_M 파일 두개가 따로 있어서 둘 다 만드는 건가요

**Comment by kimsangho611** [comment]
두 개 만드시면 됩니다. LOAD 명령어 참고 바랍니다.
