### ISSUE TITLE
음수 weight 관련 질문

### ISSUE THREAD

**Issue by hanasol** [kimsangho611/DS_Project_3_2024_2#25]
BELLMANFORD와 FLOYD 명령어를 제외하고 weight를 고려하는 다른 명령어에서는 음수인 weight값이 존재하면 에러 코드를 출력하는 건지 이런 경우는 존재하지 않는지 궁금합니다

**Comment by kimsangho611** [comment]
해당 경우는 채점시 고려하지 않을 예정입니다.
