### ISSUE TITLE
방향성 관련 질문

### ISSUE THREAD

**Issue by park092211** [kimsangho611/DS_Project_3_2024_2#26]
과제 설명 pdf의 예시에서 
0 6 2 0  0  0 0
0 0 0 5  0  0 0
0 7 0 0  3  8 0
0 0 0 0  0  0 3
0 0 0 4  0  0 0
0 0 0 0  0  0 1
0 0 0 0 10 0 0 의 경우를 살펴보면  BFS와 DFS일 때 양방향이라고 하면 그래프 자체가 대칭이여야 양방향 자체가 성립이 가능한 거 아닌가요? 위를 예시로 0과 1이 연결되어있으면 1도 0과 연결되어있어야 하는 거 아닌가요? 아니면 weight가 0이여도 일단 그냥 연결되어있다고 생각하고 구현해야하는건가요?

**Comment by kimsangho611** [comment]
방향성이 필요 없는 명령어의 경우 가중치를 무시하고 연결되었다고 생각하고 구현하면 됩니다.
