### ISSUE TITLE
getAdjacentEdges 함수 관련해서 질문드립니다.

### ISSUE THREAD

**Issue by DwKwCs** [kimsangho611/DS_Project_3_2024_2#27]
getAdjacentEdges 함수는 방향성을 가지는 edge만을 가져올 수 있다고 생각합니다. 이때, 방향성이 필요한 알고리즘과 필요없는 알고리즘에서 모두 반드시 getAdjacentEdges 함수를 사용해서 정보를 가져와야 하는지 궁금합니다.
아니라면 다른 함수를 구현해서 다른 방식으로 edge를 가져와도 되는지 궁금합니다.

**Comment by kimsangho611** [comment]
상관없습니다.
