### ISSUE TITLE
제안서 FLOYD 출력 관련 질문

### ISSUE THREAD

**Issue by hanasol** [kimsangho611/DS_Project_3_2024_2#29]
제안서에 FLOYD를 출력한 행렬이 제안서의 그림 1.의 그래프을 출력했다고 생각하는데, 그러면 FLOYD를 출력한 행렬의 1행 2열은 1->2 정점이 연결되어있지 않으므로 값은 0이 아니고 x가 출력 되어야 한다고 생각합니다. 제 생각이 맞는지 궁금합니다.

**Comment by kimsangho611** [comment]
정점 1번에서 정점 2번으로 갈 수 있는 경로가 없으므로 x가 맞습니다.
