### ISSUE TITLE
헤더파일 중복 사용 및 사용 가능 여부

### ISSUE THREAD

**Issue by sousky-j** [kimsangho611/DS_Project_3_2024_2#3]
graph.h에 cstring과 string.h이 있는데, 두 개를 동시에 사용해야 하는 이유가 있나요?
그리고 이 두개를 사용한다는 건 STL string을 사용하면 안 되는 건가요?

**Comment by kimsangho611** [comment]
1. 구현시 필요가 없다고 판단되는 헤더는 제거해도 무방합니다.

2. string STL 사용해도 무방합니다.
