### ISSUE TITLE
예외 처리 및 그래프 관련 문의

### ISSUE THREAD

**Issue by songhye0u0** [kimsangho611/DS_Project_3_2024_2#32]
1. 그래프가 루트가 없고, 두 정점 사이의 간선이 1개만 있는 그래프인가요? 아니면 루트가 있고, 두 정점 사이의 간선이 2개 이상인 것도 있다고 고려해야 될 까요?
2. command.txt파일을 읽어오지 못할 때, 오류 코드는 어떤 것을 출력해야 하나요?
3. graph_L.txt파일에서 
3-1. 도착과 가중치 외의 인자가 있는 경우
L
7
0
1 6 7
3-2. 그래프 크기가 없는 경우
L
7 0
1 6
3-3. 도착과 가중치 쌍이 2개 이상 한 줄에 있는 경우
L
7
0
1 6 2 2
3-4.  그래프 형식 정보가 없는 경우
7
0
1 6
2 2
3-5.  그래프 형식 정보 외의 다른 인자가 있는 경우
L A
7
0
1 6
2 2
다음과 같은 케이스들을 다 예외 처리 해야하나요?

**Comment by kimsangho611** [comment]
1. 정확히 뭘 물어보는지 잘 모르겠습니다.
2. command 파일을 읽어오지 못하는 경우는 없다고 가정하면 됩니다.
3. 예외처리하시면 되지만, 채점시 해당 경우는 고려하지 않습니다.

**Comment by songhye0u0** [comment]
14주차 실습 자료에서 두 정점에 대해서 방향성이 다른 모서리가 있습니다. 예를 들어서, 1번이랑 2번 정점이 있다고 하면 1->2 (가중치 a)로 가는 방향이랑 2->1(가중치 b)로 가는 방향 이렇게 2개의 정점에 대해서 방향성이 다른 선분도 있다고 모든 명령어에서 고려해야 하는 거죠? 이때 고려해야 한다면,  Kruskal 명령어를 실행하면 가중치는 a와 b중 가중치가 작은 것만 출력하면 되는 걸까요?

**Comment by kimsangho611** [comment]
Kruskal 명령어 채점시 해당 경우는 고려하지 않을 예정입니다.

그러나 구현하신다면 두 정점 사이의 평균 가중치를 출력하시면 될 거 같습니다.
