### ISSUE TITLE
방향성 관련 질문

### ISSUE THREAD

**Issue by Hagyeong13** [kimsangho611/DS_Project_3_2024_2#34]
#22 
22번 이슈에서는 제안서에 명시된 대로 방향성이 없다고 가정하면 된다고 작성되어 양방향 출력이 맞다고 생각하였는데,
#6 
6번 이슈에서는 제안서 출력인 0 -> 1 -> 2 -> 4 -> 3 -> 6 -> 5 대신 0 -> 1 -> 3 -> 6 -> 4 -> 2 -> 5의 출력이 맞다고 작성되어 있습니다.
6번 이슈의 답으로 볼 경우 단방향을 고려 해야 한다고 판단되는데,
22번 이슈에서 답하신 방향성이 없다고 말씀하신 것이 양방향을 뜻하는 것인지, 단방향을 뜻하는 것인지 궁금합니다.

**Comment by kimsangho611** [comment]
양방향 출력이 맞습니다. 

#6 번 이슈를 제가 잘못 읽어서 그런것이니 공지해두겠습니다.
