### ISSUE TITLE
리눅스 코드 실행 관련 질문

### ISSUE THREAD

**Issue by 230759264** [kimsangho611/DS_Project_3_2024_2#35]
리눅스 환경에서 
git clone https://github.com/DSLDataStorage/DS_Project_3_2022_2.git 해당 코드 실행시 
![스크린샷 2024-12-09 015308](https://github.com/user-attachments/assets/8539487d-41bd-40ea-8719-aa2e027cc543)
다음과 같이 깃허브 로그인 창이 뜨는데 자신의 깃허브 계정 정보를 입력하면 되는 건가요?
이전 과제에서는 이런 입력이 이루어지지 않고 바로 base 코드들을 다운 받을 수 있었어서 질문 드립니다.

**Comment by kimsangho611** [comment]
네 맞습니다
