### ISSUE TITLE
kruskal 관련 질문

### ISSUE THREAD

**Issue by seolbea** [kimsangho611/DS_Project_3_2024_2#37]
kruskal에서 방향성은 없지만 가중치는 존재한다면 데이터가 들어왔을 때, (시작점, 도착점)[가중치]라고 하면 만약에 (1,2)[10] , (2,1)[16] 같은 Edge 데이터가 존재하면 가중치를 어떻게 처리해야 하나요?

**Comment by kimsangho611** [comment]
#32 참고바랍니다.
