### ISSUE TITLE
딜레이 제출 관련 질문 드립니다

### ISSUE THREAD

**Issue by hj-ta** [kimsangho611/DS_Project_3_2024_2#38]
과제를 이미 제출했는데 아쉬운 부분이있고, 개선의 여지가 보여서 수정해서 제출하고 싶은데 딜레이 제출의 감점폭이 어느정도인지 몰라 고민하다, 일요일임에도 불구하고 질문드립니다.  주말에 죄송합니다.

1. 딜레이 제출에 대한 감점이 몇퍼센트인가요?

2.  코드의 일부만 수정하더라도 전체 점수자체가 감점 되어 채점 되는건가요? 
예를들어 벨만 , 크루스칼 로직만 고치더라도 전체 코드 점수에서 감점 되는건지 궁금합니다

**Comment by kimsangho611** [comment]
1. 10%입니다
2. 전체 점수에서 감점됩니다.
