### ISSUE TITLE
DFS 방문 순서

### ISSUE THREAD

**Issue by sousky-j** [kimsangho611/DS_Project_3_2024_2#6]
그래프 데이터가 다음과 같이 주어질 때, 어느 것이 올바른 출력인가요?
[0] -> (1,6) -> (2,2)
[1] -> (3,5)
[2] -> (1,7) -> (4,3) -> (5,8)
[3] -> (6,3)
[4] -> (3,4)
[5] -> (6,1)
[6] -> (4,10)
start vertex는 0 입니다.

1. 0 -> 1 -> 3 -> 6 -> 4 -> 2 -> 5
2. 0 -> 2 -> 5 -> 6 -> 4 -> 3 -> 1

제안서 예시는 0 -> 1 -> 2 -> 4 -> 3 -> 6 -> 5 이라고 나와있어 단순 예시인건지 헷갈려 질문드립니다.

**Comment by kimsangho611** [comment]
0 -> 1 -> 3 -> 6 -> 4 -> 2 -> 5가 맞습니다.

**Comment by kimsangho611** [comment]
DFS는 방향성과 가중치가 없는 그래프에서 수행하므로 학생이 주어진 그래프에서 가중치는 고려하지 않습니다. 

따라서 제안서의 예시가 맞습니다.

**Comment by kimsangho611** [comment]
1번이 맞습니다.

**Comment by kimsangho611** [comment]
양방향 출력을 가정하므로 

0-> 1 -> 2 -> 4 -> 3 -> 6 -> 5가 맞습니다.
