### ISSUE TITLE
그래프 정보 관련 문의드립니다.

### ISSUE THREAD

**Issue by parkwonkuku** [kimsangho611/DS_Project_3_2024_2#7]
이번 과제에서 제공된 코드 중에서 ListGraph 생성자에
m_List를 m_List = new map<int, int>[size]; 와 같이 선언되어있는데

그렇다면 그래프 정보에서 size보다는 작은 값으로만 들어오는건가요?

아니면 예외 처리를 해야하나요?

예를 들어 아래와 같은 데이터가 들어온다고 가정하면 insert할 때 예외 처리를 해야하는 상황이 발생합니다.

L
3
0
1 2
1
2 3
3
0 4
1 1

**Comment by kimsangho611** [comment]
예외처리하시면 됩니다.
