### ISSUE TITLE
그래프 데이터의 방향성

### ISSUE THREAD

**Issue by sousky-j** [kimsangho611/DS_Project_3_2024_2#8]
그래프 데이터가 방향성을 갖지 않는다는 조건인 탐색의 경우,
V1 -> (V2,W)인 데이터를 V2 -> (V2,-W)로 데이터를 늘려 수행해야 하는건가요?

예로, bfs, dfs를 수행할 때 그래프 데이터에 0 ->1 이라는 데이터가 있다면
1 -> 0 이라는 데이터도 추가로 넣어서 탐색을 수행해야 하는 건가요?

**Comment by sousky-j** [comment]
"각 명령어는 방향성과 가중치가 없는 그래프에서 수행 가능하므로 방향성과 그래프의 가중치가
없다고 가정하고 수행한다." 라고 하셔서 데이터 추가 없이 진행하면 될까요?

**Comment by kimsangho611** [comment]
데이터 추가 없이 데이터에서 가중치가 없다고 가정하고 구현하시면 됩니다.
